name: main

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile
      - run: yarn type
      - run: yarn lint
      - run: yarn test --ci
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

  print-secret:
    runs-on: ubuntu-latest

    steps:
      - name: check current secret XXX_TEST
        run: echo $XXX_TEST | tr a-z A-Z
        env:
          XXX_TEST: ${{ secrets.XXX_TEST }}

      - name: check current secret YYY_TEST
        run: echo $YYY_TEST | tr a-z A-Z
        env:
          YYY_TEST: ${{ secrets.YYY_TEST }}
