name: print-secret

on:
  workflow_dispatch:

jobs:
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - name: print current secret XXX_TEST
        run: echo "XXX_TEST=${XXX_TEST:0:1}.${XXX_TEST:1}"
        env:
          XXX_TEST: ${{ secrets.XXX_TEST }}
